# Generated by Django 3.2.3 on 2021-08-12 10:13

import django.core.validators
from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.PositiveSmallIntegerField()),
                ('birth_date', models.DateField()),
                ('nationality', models.CharField(choices=[('KENYAN', 'KENYAN'), ('UGANDAN', 'UGANDAN'), ('RWANDESE', 'RWANDESE'), ('SOUTH SUDANESE', 'SOUTH SUDANESE')], default=None, max_length=20)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('NON-BINARY', 'NON-BINARY'), ('TRANSGENDER', 'TRANSGENDER')], default='FEMALE', max_length=20)),
                ('student_id', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('admission_date', models.DateField()),
                ('guardian_name', models.CharField(max_length=30)),
                ('guardian_phone_number', models.CharField(max_length=20)),
                ('medical_report', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d')),
                ('room_number', models.PositiveSmallIntegerField()),
                ('class_name', models.CharField(max_length=20)),
                ('academic_year', models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1984), student.models.max_value_current_year])),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
