# Generated by Django 3.2.3 on 2021-08-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('KENYAN', 'KENYAN'), ('UGANDAN', 'UGANDAN'), ('RWANDESE', 'RWANDESE'), ('SOUTH SUDANESE', 'SOUTH SUDANESE')], max_length=20),
        ),
    ]
